name: Test

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test1:
    name: "matplotlib 3.9.1, contourpy 1.2.1"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install matplotlib and contourpy
        run: |
          python -m pip install "matplotlib==3.9.1" "contourpy==1.2.1"
          python -m pip list
      - name: Run tests
        run: |
          python test_without.py
          python test_with.py

  test2:
    name: "matplotlib 3.9.0, contourpy nightly"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install matplotlib and contourpy
        run: |
          python -m pip install "matplotlib==3.9.0"
          python -m pip install --only-binary=:all: --pre --upgrade --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple contourpy
          python -m pip list
      - run: python test_without.py
      - run: python test_with.py

  test3:
    name: "matplotlib 3.9.1, contourpy nightly"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install matplotlib and contourpy
        run: |
          python -m pip install "matplotlib==3.9.1"
          python -m pip install --only-binary=:all: --pre --upgrade --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple contourpy
          python -m pip list
      - run: python test_without.py
      - run: python test_with.py

  test4:
    name: "matplotlib nightly, contourpy nightly"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install matplotlib and contourpy
        run: |
          python -m pip install --only-binary=:all: --pre --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple contourpy matplotlib
          python -m pip list
      - run: python test_without.py
      - run: python test_with.py

  test5:
    name: "matplotlib 3.9.1 from source, contourpy nightly"
    runs-on: "windows-latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install matplotlib and contourpy
        run: |
          python -m pip install -v --no-binary=matplotlib "matplotlib==3.9.1" -Csetup-args=-Dvsenv=true
          python -m pip install --only-binary=:all: --pre --upgrade --extra-index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple contourpy
          python -m pip list
      - run: python test_without.py
      - run: python test_with.py
